## 테스트 코드 작성하기

어제 ProductRestController를 단위 테스트를 끝냈고, 

오늘 CartRestController와 OrderRestController 단위테스트 코드를 작성했다.

OrderRestController의 경우 나름대로 Service도 만들고(Repository 대신 Mock 데이터를 이용해서 만들었다.)

Order의 경우 URL 경로로 Id가 넘어오는 경우 (/order/{id}) DB에서 Id를 조회한 후 Id를 비교하는 과정이 필요하다. 

이 과정은 비즈니스 로직이므로 Service에서 처리해야 한다.

그래서 id가 다를 경우 에러를 던지도록 했다.

여기서 체크 에러랑 언체크 에러가 헷갈려서 잠깐 헤맸다.

---

### 복습(체크 언체크 예외)

![Untitled](https://github.com/boseungk/TIL/assets/95980754/81a1dc50-99d3-4b04-b80e-97acf34fcb1f)

- Throwable : 최상위 예외이다. 하위에 Exception 과 Error 가 있다.
- Error : 메모리 부족이나 심각한 시스템 오류와 같이 애플리케이션에서 복구 불가능한 시스템 예외이다. 애플리케이션 개발자는 이 예외를 잡으려고 해서는 안된다.
    - 상위 예외를 catch 로 잡으면 그 하위 예외까지 함께 잡는다. 따라서 애플리케이션 로직에서는 Throwable 예외도 잡으면 안되는데, 앞서 이야기한 Error 예외도 함께 잡을 수 있기 때문이다. 애플리케이션 로직은 이런 이유로 Exception 부터 필요한 예외로 생각하고 잡으면 된다.
    - 참고로 Error 도 언체크 예외이다.
- Exception : 체크 예외
    - 애플리케이션 로직에서 사용할 수 있는 실질적인 최상위 예외이다.
    - Exception 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다. 단 RuntimeException 은 예외로 한다.
- RuntimeException : 언체크 예외, 런타임 예외
    - 컴파일러가 체크 하지 않는 언체크 예외이다.
    - RuntimeException 과 그 자식 예외는 모두 언체크 예외이다.
    - RuntimeException 의 이름을 따라서 RuntimeException 과 그 하위 언체크 예외를 런타임 예외라고 많이 부른다

### Relation Source

- ****[스프링 DB 1편 - 데이터 접근 핵심 원리](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-db-1)****

---

우리가 사용할 예외는 런타임 에러를 상속했기 때문에 언체크 예외이다.

```java
@Getter
public class Exception404 extends RuntimeException {
//..
}
```

그래서 언체크 예외이기 때문에 예외 던지기(throws Exception)를 하지 않아도 되지만, 명시적으로 예외를 표시하고 싶어서 아래와 같이 예외를 적어주었다.

```java
public OrderResponse.FindByIdDTO findById(int id) throws Exception404 {
        Order order = fakeStore.getOrderList().stream().filter(p -> p.getId() == id).findFirst().orElse(null);
        if(order == null){
            throw new Exception404("해당 상품을 찾을 수 없습니다");
        }
        List<Item> itemList = fakeStore.getItemList();
        OrderResponse.FindByIdDTO responseDTO = new OrderResponse.FindByIdDTO(order, itemList);
        return responseDTO;
    }
```

그리고 `orderService.findById(id)`에서 Id를 조회하다가 런타임 에러가 발생하면 try - catch로 에러를 처리할 수 있게 아래와 같이 처리해주었다.

```java
@GetMapping("/orders/{id}")
    public ResponseEntity<?> findById(@PathVariable int id, HttpServletRequest request, @AuthenticationPrincipal CustomUserDetails userDetails) {
        try{
            OrderResponse.FindByIdDTO responseDTO = orderService.findById(id);
            return ResponseEntity.ok().body(ApiUtils.success(responseDTO));
        }catch (Exception404 e) {
            return globalExceptionHandler.handle(e, request);
        }
    }
```

그리고 아래와 같이 먼저 성공 시나리오의 테스트 코드를 작성했다.

```java
@WithMockUser(username = "ssar@nate.com", roles = "USER")
    @Test//findById() 성공 테스트
    public void findById_test() throws Exception{
        /*
        @SpringBootTest로 Repository를 빈으로 등록해서 id를 가져오는 대신
        MockMvc로 가볍게 테스트하기 위해 Mock 데이터를 이용해서 id 값을 가져왔습니다.
         */
        //given
        int id = fakeStore.getOrderList().get(0).getId();

        Order order = fakeStore.getOrderList().get(0);
        List<Item> itemList = fakeStore.getItemList();

        //stub
        Mockito.when(orderService.findById(id)).thenReturn(new OrderResponse.FindByIdDTO(order, itemList));

        //when
        ResultActions result = mvc.perform(
                MockMvcRequestBuilders
                        .get("/orders/"+id)
        );
        String responseBody = result.andReturn().getResponse().getContentAsString();
        System.out.println("테스트 : "+responseBody);

        // then
        result.andExpect(MockMvcResultMatchers.jsonPath("$.success").value("true"));
        result.andExpect(MockMvcResultMatchers.jsonPath("$.response.products[0].id").value(1));
        result.andExpect(MockMvcResultMatchers.jsonPath("$.response.products[0].productName").value("기본에 슬라이딩 지퍼백 크리스마스/플라워에디션 에디션 외 주방용품 특가전"));
        result.andExpect(MockMvcResultMatchers.jsonPath("$.response.products[0].items[0].id").value(1));
        result.andExpect(MockMvcResultMatchers.jsonPath("$.response.products[0].items[0].optionName").value("01. 슬라이딩 지퍼백 크리스마스에디션 4종"));
        result.andExpect(MockMvcResultMatchers.jsonPath("$.response.products[0].items[0].quantity").value(5));
        result.andExpect(MockMvcResultMatchers.jsonPath("$.response.products[0].items[0].price").value(50000));
    }
```

그리고 order Id가 아닌 Id로 조회했을 때, 에러가 발생하는 시나리오를 가정하고 아래와 같이 실패하는 테스트 케이스를 작성했다.

```java
@WithMockUser(username = "ssar@nate.com", roles = "USER")
    @Test//findById() 성공 테스트
    public void findById_wrong_id_test() throws Exception{
        //given
        final int id = 1000; // 없는 id 값

        Order order = fakeStore.getOrderList().get(0);
        List<Item> itemList = fakeStore.getItemList();

        //stub
        Mockito.when(orderService.findById(id)).thenThrow(new Exception404("해당 상품을 찾을 수 없습니다"));

        //when
        ResultActions result = mvc.perform(
                MockMvcRequestBuilders
                        .get("/orders/"+id)
        );
        String responseBody = result.andReturn().getResponse().getContentAsString();
        System.out.println("테스트 : "+responseBody);

        // then
        result.andExpectAll(
                status().is4xxClientError(), // 404 오류 확인
                MockMvcResultMatchers.jsonPath("$.success").value("false")
        );
    }
```

테스트 코드는 다 작성하긴 했는데, Controller의 코드들을 리팩토링 좀더 해볼지는 내일 고민해봐야겠다..